---
title: "COMPSCIX 415.2 Homework 1"
author: "Naga Katragadda"
date: 2018-02-05
output: html_document
---

```{r load_packages, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mdsr)
library(tidyverse)
data("WorldCities")
?WorldCities
```
```{r}
knitr::opts_chunk$set(echo = TRUE)
glimpse(WorldCities)
WorldCities <- head(WorldCities,200) #200 rows
country_col <- WorldCities$country
unique(country_col)

region_col <- WorldCities$region
unique(region_col)

WorldCities %>% select(country) %>% unique()

WorldCities %>% ggplot(aes(x=population)) + geom_histogram()

WorldCities %>% ggplot(aes(x=population)) + geom_histogram() + xlab('City Population')

```

```{r}
knitr::opts_chunk$set(echo = TRUE)

WorldCities %>% ggplot(aes(x=population)) + geom_histogram() + xlab('Total City Population') + ylab('Total Count') + ggtitle("my title") + theme_bw(base_size = 10, base_family = "") # theme_bw reference http://ggplot2.tidyverse.org/reference/ggtheme.html#examples

```

## R Markdown

My Github repository for my assignments can be found at this URL: [https://github.com/NagaChalapathiRao/compscix-415-2-assignments]

There are 23,018 observations and 10 variables in WorldCities data set.
code, name, latitude, longitude, country, countryRegion, population, regionCode, region and date are the variables considered for the data set.



